name = "NumOptBase"
uuid = "19474dce-faed-4c37-be94-3eba84df10eb"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.0"

[deps]
Unitless = "c904d999-9673-4878-a3dd-e3ef1851788a"

[compat]
Unitless = "2"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
