name = "NumOptBase"
uuid = "19474dce-faed-4c37-be94-3eba84df10eb"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.12"

[deps]
ArrayTools = "1dc0ca97-c5ce-4e77-ac6d-c576ac9d7f27"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"

[compat]
ArrayTools = "0.2.7, 0.3"
CUDA = "1"
LoopVectorization = "0.8, 0.9, 0.10, 0.11, 0.12"
Requires = "1.3"
TypeUtils = "0.2, 0.3"
julia = "1.2"

[extensions]
NumOptBaseCUDAExt = "CUDA"
NumOptBaseLoopVectorizationExt = "LoopVectorization"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CUDA", "LoopVectorization"]
