#! /usr/bin/bash
exe=`realpath "$0"`
dir=`dirname "$exe"`
for ver in 1.{2..10}; do
    echo "############## julia-$ver"
    rm -f "$dir/Manifest.toml"
    julia +$ver --project="$dir" --check-bounds=yes --depwarn=yes --color=yes \
        -e 'using Pkg; Pkg.instantiate(); include("test/runtests.jl")'
    rm -f "$dir/Manifest.toml"
done
